[package]
name = "mneq"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# 启用 wasm 的 js 特性
getrandom = { version = "0.2", features = ["js"] }
ahash = "0.8.11"
wasm-bindgen = "0.2.93"
